# Generated by Django 5.0.6 on 2024-06-20 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picture_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('file_data', models.TextField(null=True)),
                ('inf_result', models.IntegerField(blank=True, null=True)),
                ('inf_conf', models.IntegerField(blank=True, null=True)),
                ('cap_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('inference_ms', models.DurationField(blank=True, default=0)),
                ('robot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.robot')),
            ],
        ),
    ]
