# Generated by Django 5.0.6 on 2024-06-20 06:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('on_time', models.DateTimeField()),
                ('off_time', models.DateTimeField()),
                ('active_time', models.DurationField(default=datetime.timedelta(0))),
                ('scans', models.IntegerField(default=0)),
                ('wifi', models.IntegerField(default=0)),
                ('cam', models.IntegerField(default=0)),
                ('robot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.robot')),
            ],
        ),
    ]
